name: SkyBlockReloaded
authors:
  - Schleimer
  - nerotvlive
version: 1.0.0
main: de.schleimer.skyblockre.Main
commands:
  island:
    aliases:
      - is
      - in
      - insel
  spawn:
    description: Teleports you to the SkyBlock spawn
  template:
    description: Teleports you to the SkyBlock template
  build:
    description: Toggles the permissions to build everywhere
  warp:
    description: Command to set, teleport to or toggle a warp